### ISSUE TITLE
지도 로드된 뒤 팝업을 종료하면 다음 팝업 실행 시 프로그램이 종료되는 오류

### ISSUE THREAD

**Issue by donghoony** [konkuk-PlaceList/PlaceList#14]
`mMap` 내 `lateinit` 이 초기화되지 않아 발생합니다

**Comment by uyagi13** [comment]
해당버그 원인 찾아서 해결했습니다.

**Comment by donghoony** [comment]
#[24884bd](https://github.com/konkuk-PlaceList/PlaceList/commit/24884bdacd5ed10ee788da23f72ebf7115b9f857)
